// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA422dss9kDyRhwqJPEx4CyEfnqoTqtOyU',
    appId: '1:535267910277:web:8e989fcf66379cb933bfec',
    messagingSenderId: '535267910277',
    projectId: 'vistagram-a4266',
    authDomain: 'vistagram-a4266.firebaseapp.com',
    storageBucket: 'vistagram-a4266.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsYPbzrJpysAoBgmWOxpKoiKvx2zF9a2o',
    appId: '1:535267910277:android:e71d7915166186ad33bfec',
    messagingSenderId: '535267910277',
    projectId: 'vistagram-a4266',
    storageBucket: 'vistagram-a4266.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU1vItd0kYgGJv5GzapvVDUX5-H74nOLU',
    appId: '1:535267910277:ios:243a72349f1bff7633bfec',
    messagingSenderId: '535267910277',
    projectId: 'vistagram-a4266',
    storageBucket: 'vistagram-a4266.firebasestorage.app',
    iosBundleId: 'com.vistagram.vistagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU1vItd0kYgGJv5GzapvVDUX5-H74nOLU',
    appId: '1:535267910277:ios:243a72349f1bff7633bfec',
    messagingSenderId: '535267910277',
    projectId: 'vistagram-a4266',
    storageBucket: 'vistagram-a4266.firebasestorage.app',
    iosBundleId: 'com.vistagram.vistagram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA422dss9kDyRhwqJPEx4CyEfnqoTqtOyU',
    appId: '1:535267910277:web:965f16f8a579fd0b33bfec',
    messagingSenderId: '535267910277',
    projectId: 'vistagram-a4266',
    authDomain: 'vistagram-a4266.firebaseapp.com',
    storageBucket: 'vistagram-a4266.firebasestorage.app',
  );
}
